### ISSUE TITLE
Instructions for code review

### ISSUE THREAD

**Issue by twink1e** [CS2103AUG2016-W09-C4/main#110]
Good job with your progress so far 👍 

I have created an issue each for your collated code (`main` and `test` combined). Please identify by your matric number. After reading the comments, you may want edit your codes accordingly, or you can choose not to change and leave comments about why you wrote that way. Please close the issue after you are done.

In future code reviews, please submit a PR to `nus-cs2103-AY1617S1/addressbook-level4` with all your finalised collated files, so that I can comment in the diff view. It will then be easier for me to comment and for you to read :)

**Comment by JasonScourge** [comment]
Is it fine if you review our code?

**Comment by ashley-si** [comment]
Sure! After you have finalised your collated code, make a pull request to nus-cs2103-AY1617S1/addressbook-level4, and I will be able to comment next to your codes
