### ISSUE TITLE
prohibits uppercase character in package definition 

### ISSUE THREAD

**Issue by xpdavid** [CS2103AUG2016-W09-C4/main#85]
Refer to here
https://www.codacy.com/app/xp-xiaopu/main/issues?bid=3817435&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbOTAzXX1d

**Comment by JasonScourge** [comment]
The issues in codacy seems to be missing; do we still need to work on this?
